//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoColonna1308.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Childs
    {
        public int id_child { get; set; }
        public int id_chel { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
