//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoColonna1308.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public int IdVac { get; set; }
        public int IdChel { get; set; }
        public System.DateTime VacStart { get; set; }
        public System.DateTime VacFinish { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
